//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace EF4TestsWinApp
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Model5Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Model5Container object using the connection string found in the 'Model5Container' section of the application configuration file.
        /// </summary>
        public Model5Container() : base("name=Model5Container", "Model5Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model5Container object.
        /// </summary>
        public Model5Container(string connectionString) : base(connectionString, "Model5Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model5Container object.
        /// </summary>
        public Model5Container(EntityConnection connection) : base(connection, "Model5Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TimeStampTest> TimeStampTests
        {
            get
            {
                if ((_TimeStampTests == null))
                {
                    _TimeStampTests = base.CreateObjectSet<TimeStampTest>("TimeStampTests");
                }
                return _TimeStampTests;
            }
        }
        private ObjectSet<TimeStampTest> _TimeStampTests;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TimeStampTests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTimeStampTests(TimeStampTest timeStampTest)
        {
            base.AddObject("TimeStampTests", timeStampTest);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model5", Name="TimeStampTest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TimeStampTest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TimeStampTest object.
        /// </summary>
        /// <param name="f1">Initial value of the F1 property.</param>
        public static TimeStampTest CreateTimeStampTest(global::System.Int32 f1)
        {
            TimeStampTest timeStampTest = new TimeStampTest();
            timeStampTest.F1 = f1;
            return timeStampTest;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 F1
        {
            get
            {
                return _F1;
            }
            set
            {
                if (_F1 != value)
                {
                    OnF1Changing(value);
                    ReportPropertyChanging("F1");
                    _F1 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("F1");
                    OnF1Changed();
                }
            }
        }
        private global::System.Int32 _F1;
        partial void OnF1Changing(global::System.Int32 value);
        partial void OnF1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String F2
        {
            get
            {
                return _F2;
            }
            set
            {
                OnF2Changing(value);
                ReportPropertyChanging("F2");
                _F2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("F2");
                OnF2Changed();
            }
        }
        private global::System.String _F2;
        partial void OnF2Changing(global::System.String value);
        partial void OnF2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private global::System.Byte[] TS
        {
            get
            {
                return StructuralObject.GetValidValue(_TS);
            }
            set
            {
                OnTSChanging(value);
                ReportPropertyChanging("TS");
                _TS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TS");
                OnTSChanged();
            }
        }
        private global::System.Byte[] _TS;
        partial void OnTSChanging(global::System.Byte[] value);
        partial void OnTSChanged();

        #endregion
    
    }

    #endregion
    
}
